site_name: Marvin
site_description: 'The AI Engineering Framework'
site_url: https://askmarvin.ai
docs_dir: docs
repo_url: https://github.com/prefecthq/marvin

nav:
  - Docs:
    - welcome/what_is_marvin.md
    - Getting started:
      - welcome/installation.md
      - welcome/quickstart.md
      # - help/legacy_docs.md

    # - Overview: welcome/overview.md

    - Text and data:
      - AI functions: ai/function.md
      - Structured data: ai/casting.md
      - Entity extraction: ai/extraction.md
      - Classification: ai/classification.md
      - Generating synthetic data: ai/generation.md

    - Images:
      - Creating images: ai/painting.md
      # - Captioning: ai/function.md

    - Audio:
      - Text-to-speech: ai/speech.md
    # - Transcription: ai/function.md
      
    - Configuration: 
      - Settings: configuration/settings.md

    # - Examples:
    #   - Slackbot: examples/slackbot.md
    #   - GitHub Digest: examples/github_digest.md
  - API reference:
    - marvin: api_reference/marvin.md
    - AI modules:
      - marvin.ai.text: api_reference/ai/text.md
      - marvin.ai.images: api_reference/ai/images.md
      - marvin.ai.audio: api_reference/ai/audio.md
      
    - Object schemas: 
      - marvin.requests: api_reference/requests.md
    - Settings:
      - marvin.settings: api_reference/settings.md
    - Utilities:
      - marvin.utilities.asyncio: api_reference/utilities/asyncio.md
      - marvin.utilities.jinja: api_reference/utilities/jinja.md
      - marvin.utilities.logging: api_reference/utilities/logging.md
      - marvin.utilities.tools: api_reference/utilities/tools.md
  - Cookbook:
    - Entity deduplication: examples/deduplication.md
    - Deploying an API:
      - Basic extraction API: examples/extraction_api.md
      - Basic classification API: examples/classification_api.md
  - Community:
    - community/index.md
    - Feedback 💙: community/feedback.md
    - Contributing: community/development_guide.md


theme:
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - content.code.copy
    - content.code.select
    - content.code.annotate
  palette:
    primary: custom
  name: material
  custom_dir: docs/overrides
  logo: assets/images/logos/askmarvin_mascot.jpeg
  favicon: assets/images/logos/askmarvin_mascot.jpeg

plugins:
  - search
  - markdownextradata
  - social:
      cards: !ENV [MKDOCS_SOCIAL_CARDS, false]
      cards_layout_options:
        font_family: Inter
        background_color: "#2d6df6"
  - awesome-pages
  - autolinks 
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: false
            show_root_heading: false
            show_root_toc_entry: false
            show_object_full_path: false
            show_category_heading: false
            show_bases: false
            show_submodules: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_if_no_docstring: false
            show_signature: false
            heading_level: 2
            filters: ["!^_"]
          import:
          - https://docs.python-requests.org/en/master/objects.inv
watch:
  - src
  - docs
  - mkdocs.yml

hooks:
  - docs/hooks.py

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      title: On this page

extra:
  get_started: welcome/what_is_marvin
  hero:
    title: 'The AI Engineering Framework'
    description: 'Marvin is a lightweight AI engineering framework for building natural language interfaces that are reliable, scalable, and easy to trust.'
  announcement:
    title: "Marvin 2.0 is here!"
    url: https://github.com/PrefectHQ/marvin/releases/tag/v2.0.0
  analytics:
    provider: google
    property: G-2MWKMDJ9CM
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/prefecthq/marvin
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Kgw4HpcuYG
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/askmarvinai


extra_css:
  - /static/css/global.css
  - /static/css/badges.css
  - /static/css/custom.css
  - /static/css/mkdocstrings.css